CREATE TABLE VACCIN(
MAVC VARCHAR(10) PRIMARY KEY,
TENVC NVARCHAR(30) NOT NULL,
DONGIA DECIMAL(18,3) NOT NULL,
DONVITINH DECIMAL(3,2) NOT NULL,
NUOCSX NVARCHAR(20) NOT NULL,
NSX DATE NOT NULL,
HSD DATE NOT NULL,
SLTK INT NOT NULL,
MALOAIVC VARCHAR(15) NOT NULL)

CREATE TABLE LOAIVACCIN(
MALOAIVC VARCHAR(15) PRIMARY KEY,
CHUNGLOAI NVARCHAR(MAX) NOT NULL,
CONGDUNG NVARCHAR(MAX) NOT NULL,
MAKHO VARCHAR(10) NOT NULL)

CREATE TABLE KHO(
MAKHO VARCHAR(10) PRIMARY KEY,
SUCCHUA INT NOT NULL)

CREATE TABLE PHIEUKTSK(
MAPHIEUKTSK VARCHAR(10) PRIMARY KEY,
NGAYKT DATE,
NOIDUNG NVARCHAR(MAX) NOT NULL,
MAKH VARCHAR(10) NOT NULL,
MABS VARCHAR(10) NOT NULL)

CREATE TABLE BACSI(
MABS VARCHAR(10) PRIMARY KEY,
HOBS NVARCHAR(30) NOT NULL,
TENBS NVARCHAR(15) NOT NULL,
DIACHIBS NVARCHAR(40) NOT NULL,
GTBS NVARCHAR(10) CHECK (GTBS IN (N'Nam',N'Nữ')),
NSBS DATE NOT NULL,
SDTBS VARCHAR(10) NOT NULL)

CREATE TABLE KHACHHANG(
MAKH VARCHAR(10) PRIMARY KEY,
HOKH NVARCHAR(30) NOT NULL,
TENKH NVARCHAR(15) NOT NULL,
DIACHIKH NVARCHAR(MAX) NOT NULL,
GTKH NVARCHAR(10) CHECK (GTKH IN (N'Nam',N'Nữ')),
NSKH DATE NOT NULL,
NGUOIBT NVARCHAR(30),
SDTKH VARCHAR(10) NOT NULL)

CREATE TABLE NHANVIEN(
MANV VARCHAR(10) PRIMARY KEY,
HONV NVARCHAR(30) NOT NULL,
TENNV NVARCHAR(15) NOT NULL,
DIACHINV NVARCHAR(MAX) NOT NULL,
GTNV NVARCHAR(10) CHECK (GTNV IN (N'Nam',N'Nữ')),
NSNV DATE NOT NULL,
SDTNV VARCHAR(10) NOT NULL)

CREATE TABLE HOADON(
MAHD VARCHAR(10) PRIMARY KEY,
TONGTIEN DECIMAL(18,3) NOT NULL,
NGAYTT DATE NOT NULL,
MAPT VARCHAR(10) NOT NULL)

CREATE TABLE PHIEUTIEM(
MAPT VARCHAR(10) PRIMARY KEY,
MANV VARCHAR(10) NOT NULL,
MAKH VARCHAR(10) NOT NULL,
NGAYTIEM DATE NOT NULL)

CREATE TABLE LUOTDUNG(
MAPT VARCHAR(10) NOT NULL,
MAVC VARCHAR(10) NOT NULL,
SOLUONGVC INT,
LIEUDUNG DECIMAL(3,2))

CREATE TABLE CHITIET_PN(
MAVC VARCHAR(10) NOT NULL,
MAPN VARCHAR(10) NOT NULL,
SOLUONG INT NOT NULL)

CREATE TABLE PHIEUNHAP(
MAPN VARCHAR(10) PRIMARY KEY,
MANV VARCHAR(10) NOT NULL,
NGAYNHAP DATE NOT NULL)